"""Autogenerated migration from PR

Revision ID: 025c4f6fec04
Revises: 6a6f4acfcc2e
Create Date: 2025-09-23 04:04:32.800442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '025c4f6fec04'
down_revision: Union[str, Sequence[str], None] = '6a6f4acfcc2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('recurring_order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'recurring_order', ['recurring_order_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'recurring_order_id')
    # ### end Alembic commands ###
