"""add pending_role_ids to notifications

Revision ID: 0f529c470393
Revises: 98df8301ae46
Create Date: 2026-02-16 22:35:37.433719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f529c470393'
down_revision: Union[str, Sequence[str], None] = '98df8301ae46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('pending_role_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'pending_role_ids')
    # ### end Alembic commands ###
