"""refactor_order_date_fields_to_due_date_and_payment_date

Revision ID: 2f76adc5966b
Revises: 1e745f682fff
Create Date: 2026-01-23 17:30:29.694473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f76adc5966b'
down_revision: Union[str, Sequence[str], None] = '1e745f682fff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('order', sa.Column('payment_date', sa.DateTime(), nullable=True))
    op.drop_column('order', 'generation_date')
    op.drop_column('order', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('order', sa.Column('generation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('order', 'payment_date')
    op.drop_column('order', 'due_date')
    # ### end Alembic commands ###
