"""add billing models and user invitation system

Revision ID: 333a94575eb7
Revises: 46fa11ccdeb8
Create Date: 2025-12-23 10:06:51.270488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '333a94575eb7'
down_revision: Union[str, Sequence[str], None] = '46fa11ccdeb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_method',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('last4', sa.String(), nullable=False),
    sa.Column('expiry_month', sa.Integer(), nullable=True),
    sa.Column('expiry_year', sa.Integer(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('stripe_payment_method_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_payment_method_id')
    )
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('billing_type', sa.String(), nullable=False),
    sa.Column('current_period_start', sa.DateTime(), nullable=False),
    sa.Column('current_period_end', sa.DateTime(), nullable=False),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('trial_end', sa.DateTime(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('tier_id', sa.Integer(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tier_id'], ['tier.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id'),
    sa.UniqueConstraint('stripe_subscription_id')
    )
    op.create_table('billing_invoice',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('invoice_number', sa.String(), nullable=False),
    sa.Column('invoice_date', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.Column('tax', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('payment_type', sa.String(), nullable=True),
    sa.Column('manual_payment_method', sa.String(), nullable=True),
    sa.Column('manual_payment_note', sa.Text(), nullable=True),
    sa.Column('marked_paid_by_user_id', sa.Integer(), nullable=True),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('payment_method_id', sa.Integer(), nullable=True),
    sa.Column('stripe_invoice_id', sa.String(), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(), nullable=True),
    sa.Column('billing_reason', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['marked_paid_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_method.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number'),
    sa.UniqueConstraint('stripe_invoice_id')
    )
    op.create_table('user_invitation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('invited_by_user_id', sa.Integer(), nullable=True),
    sa.Column('accepted_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accepted_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('user_invitation_role',
    sa.Column('invitation_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['invitation_id'], ['user_invitation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('invitation_id', 'role_id')
    )
    # Add tier columns - first as nullable, then update existing rows, then set NOT NULL
    op.add_column('tier', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('tier', sa.Column('billing_cycle', sa.String(), nullable=True))
    op.add_column('tier', sa.Column('features', sa.JSON(), nullable=True))
    op.add_column('tier', sa.Column('stripe_price_id', sa.String(), nullable=True))
    op.add_column('tier', sa.Column('is_active', sa.Boolean(), nullable=True))

    # Update existing tier rows with default values
    op.execute("UPDATE tier SET price = 0 WHERE price IS NULL")
    op.execute("UPDATE tier SET billing_cycle = 'MONTHLY' WHERE billing_cycle IS NULL")
    op.execute("UPDATE tier SET is_active = true WHERE is_active IS NULL")

    # Now set columns to NOT NULL
    op.alter_column('tier', 'price', nullable=False)
    op.alter_column('tier', 'billing_cycle', nullable=False)
    op.alter_column('tier', 'is_active', nullable=False)

    # Add user active column
    op.add_column('user', sa.Column('active', sa.Boolean(), nullable=True))
    op.execute("UPDATE \"user\" SET active = true WHERE active IS NULL")
    op.alter_column('user', 'active', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'active')
    op.drop_column('tier', 'is_active')
    op.drop_column('tier', 'stripe_price_id')
    op.drop_column('tier', 'features')
    op.drop_column('tier', 'billing_cycle')
    op.drop_column('tier', 'price')
    op.drop_table('user_invitation_role')
    op.drop_table('user_invitation')
    op.drop_table('billing_invoice')
    op.drop_table('subscription')
    op.drop_table('payment_method')
    # ### end Alembic commands ###
