"""add_status_to_order

Revision ID: 384a24a274db
Revises: c33eed8ebb8d
Create Date: 2026-02-07 11:22:50.436297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '384a24a274db'
down_revision: Union[str, Sequence[str], None] = 'c33eed8ebb8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    op.execute("CREATE TYPE orderstatus AS ENUM ('ACTIVE', 'CANCELLED')")
    # Add the column with the enum type
    op.add_column('order', sa.Column('status', sa.Enum('ACTIVE', 'CANCELLED', name='orderstatus', create_type=False), server_default='ACTIVE', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'status')
    op.execute("DROP TYPE orderstatus")
    # ### end Alembic commands ###
