"""Autogenerated migration from PR

Revision ID: 3ec9a48e5ddd
Revises: b19ced0a68ca
Create Date: 2025-08-15 22:41:18.100601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ec9a48e5ddd'
down_revision: Union[str, Sequence[str], None] = 'b19ced0a68ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
