"""Autogenerated migration from PR

Revision ID: 4d5c4f653bdb
Revises: a94a45d52904
Create Date: 2025-11-28 20:51:45.280671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d5c4f653bdb'
down_revision: Union[str, Sequence[str], None] = 'a94a45d52904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'recurring')
    op.drop_column('order', 'recurrence')
    op.add_column('recurring_order', sa.Column('next_generation_date', sa.DateTime(), nullable=True))
    op.add_column('recurring_order', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recurring_order', 'is_active')
    op.drop_column('recurring_order', 'next_generation_date')
    op.add_column('order', sa.Column('recurrence', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('recurring', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
