"""Add generation_date to Order model

Revision ID: 5e70de00414c
Revises: 77c97338cfd9
Create Date: 2026-01-16 01:38:04.618357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e70de00414c'
down_revision: Union[str, Sequence[str], None] = '77c97338cfd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('generation_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'generation_date')
    # ### end Alembic commands ###
