"""Remove legacy role and admin from notification table

Revision ID: 77c97338cfd9
Revises: d217d9531907
Create Date: 2026-01-16 00:32:02.805818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77c97338cfd9'
down_revision: Union[str, Sequence[str], None] = 'd217d9531907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'role')
    op.drop_column('notification', 'admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('notification', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
