"""Autogenerated migration from PR

Revision ID: 82da1e77a603
Revises: 85d2dfb7484b
Create Date: 2025-08-11 04:22:02.423399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82da1e77a603'
down_revision: Union[str, Sequence[str], None] = '85d2dfb7484b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
