"""Workflow module

Revision ID: 98df8301ae46
Revises: 7ddfc76c44dd
Create Date: 2026-02-13 09:42:10.380887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98df8301ae46'
down_revision: Union[str, Sequence[str], None] = '7ddfc76c44dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_execution',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', name='executionstatus'), nullable=False),
    sa.Column('trigger_event', sa.JSON(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_step',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('action_type', sa.Enum('UPDATE_FIELD', 'CREATE_ENTITY', name='stepactiontype'), nullable=False),
    sa.Column('action_config', sa.JSON(), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_trigger',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('event_type', sa.Enum('CREATED', 'UPDATED', 'DELETED', name='triggereventtype'), nullable=False),
    sa.Column('field_conditions', sa.JSON(), nullable=True),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_step_edge',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('from_step_id', sa.Uuid(), nullable=False),
    sa.Column('to_step_id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['from_step_id'], ['workflow_step.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_step_id'], ['workflow_step.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_step_execution',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', name='executionstatus'), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('step_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_execution.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['workflow_step.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflow_step_execution')
    op.drop_table('workflow_step_edge')
    op.drop_table('workflow_trigger')
    op.drop_table('workflow_step')
    op.drop_table('workflow_execution')
    op.drop_table('workflow')
    # ### end Alembic commands ###
