"""Autogenerated migration from PR

Revision ID: 99be9125d301
Revises: 025c4f6fec04
Create Date: 2025-09-23 04:17:50.345598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99be9125d301'
down_revision: Union[str, Sequence[str], None] = '025c4f6fec04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recurring_order', sa.Column('last_generated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recurring_order', 'last_generated_at')
    # ### end Alembic commands ###
