"""Autogenerated migration from PR

Revision ID: a94a45d52904
Revises: 99be9125d301
Create Date: 2025-11-28 20:18:15.275239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a94a45d52904'
down_revision: Union[str, Sequence[str], None] = '99be9125d301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'recurrence')
    op.drop_column('order', 'recurring')
    op.add_column('recurring_order', sa.Column('next_generation_date', sa.DateTime(), nullable=True))
    op.add_column('recurring_order', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recurring_order', 'is_active')
    op.drop_column('recurring_order', 'next_generation_date')
    op.add_column('order', sa.Column('recurring', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('order', sa.Column('recurrence', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
