"""Autogenerated migration from PR

Revision ID: b19ced0a68ca
Revises: 82da1e77a603
Create Date: 2025-08-15 22:21:44.532679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b19ced0a68ca'
down_revision: Union[str, Sequence[str], None] = '82da1e77a603'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tier',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('company', sa.Column('tier_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'company', 'tier', ['tier_id'], ['id'])
    op.drop_column('company', 'plan_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('plan_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.drop_column('company', 'tier_id')
    op.drop_table('tier')
    # ### end Alembic commands ###
