"""Autogenerated migration from PR

Revision ID: b4250ab4a8ee
Revises: 2f76adc5966b
Create Date: 2026-01-23 23:41:09.437871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4250ab4a8ee'
down_revision: Union[str, Sequence[str], None] = '2f76adc5966b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
