"""add_is_valid_to_invoice_and_revert_payment_permission

Revision ID: daf2fe3f9539
Revises: 2f76adc5966b
Create Date: 2026-01-26 22:33:10.000614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daf2fe3f9539'
down_revision: Union[str, Sequence[str], None] = '2f76adc5966b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('is_valid', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice', 'is_valid')
    # ### end Alembic commands ###
