from .auth import (
    Company,
    User,
    Notification,
    EmailVerificationToken,
    PasswordResetToken,
)

from .crm import (
    Client,
    Product,
    Order,
    OrderItem,
    OrderStatus,
    OrderType,
    PaymentStatus,
    Payment,
    PaymentKind,
    PaymentMethodType,
    Invoice,
    CustomFieldDefinition,
    ClientCustomFieldValue,
    TaskState,
    TaskStateColor,
    Task,
    task_assignee,
    Integration,
    IntegrationAuthType,
)

from .isp import (
    ServicePlan,
    ServicePlanType,
    ClientService,
    ClientServiceStatus,
    ServiceSuspension,
    SuspensionReason,
    DeviceType,
    DeviceCategory,
    Warehouse,
    InventoryItem,
    InventoryItemStatus,
    InventoryItemCondition,
    EquipmentEvent,
    EquipmentEventType,
    NetworkNodeType,
    NetworkNode,
    NetworkNodeStatus,
    NetworkLink,
    Playbook,
    ProvisioningJob,
    ProvisioningJobStatus,
    ProvisioningTrigger,
)

from .workflow import (
    WorkflowTemplate,
    Workflow,
    WorkflowTrigger,
    WorkflowStep,
    WorkflowStepEdge,
    WorkflowExecution,
    WorkflowStepExecution,
    WorkflowStatus,
    TriggerEventType,
    StepActionType,
    ExecutionStatus,
)

# Import all models here so Alembic can detect them
__all__ = [
    # Auth
    "Company",
    "User",
    "Notification",
    "EmailVerificationToken",
    "PasswordResetToken",
    # CRM
    "Client",
    "Product",
    "Order",
    "OrderItem",
    "OrderStatus",
    "OrderType",
    "PaymentStatus",
    "Payment",
    "PaymentKind",
    "PaymentMethodType",
    "Invoice",
    "CustomFieldDefinition",
    "ClientCustomFieldValue",
    "TaskState",
    "TaskStateColor",
    "Task",
    "task_assignee",
    "Integration",
    "IntegrationAuthType",
    # ISP
    "ServicePlan",
    "ServicePlanType",
    "ClientService",
    "ClientServiceStatus",
    "ServiceSuspension",
    "SuspensionReason",
    "DeviceType",
    "DeviceCategory",
    "Warehouse",
    "InventoryItem",
    "InventoryItemStatus",
    "InventoryItemCondition",
    "EquipmentEvent",
    "EquipmentEventType",
    "NetworkNodeType",
    "NetworkNode",
    "NetworkNodeStatus",
    "NetworkLink",
    "Playbook",
    "ProvisioningJob",
    "ProvisioningJobStatus",
    "ProvisioningTrigger",
    # Workflows
    "WorkflowTemplate",
    "Workflow",
    "WorkflowTrigger",
    "WorkflowStep",
    "WorkflowStepEdge",
    "WorkflowExecution",
    "WorkflowStepExecution",
    "WorkflowStatus",
    "TriggerEventType",
    "StepActionType",
    "ExecutionStatus",
]