name: Alembic Migration Autogenerate (PR)

on:
  pull_request:
    branches:
      - main
    paths:
      - "database_utils/models/**"
      - "alembic/env.py"

permissions:
  contents: write

jobs:
  autogenerate-migration:
    runs-on: ubuntu-latest
    env:
      DB_URL: ${{ secrets.DATABASE_URL }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Autogenerate Alembic migration
        run: |
          alembic revision --autogenerate -m "Autogenerated migration from PR"

      - name: Commit and push migration to PR branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add alembic/versions/
          git commit -m "ci: autogenerated Alembic migration [skip ci]" || echo "No changes to commit"
          git push origin HEAD:${{ github.head_ref }}